### ISSUE TITLE
Mumbai V3 Subgraph data different from staging aave mumbai v3

### ISSUE THREAD

**Issue by Kaushal1011** [aave/protocol-subgraphs#107]
**Describe the bug**
The data returned by the reserves query doesn't match the reserves data on the staging.aave.com platform for Mumbai v3 network!

**To Reproduce**
Query the reserves in Graphql with `underlyingAsset` field and check the reserve contract addresses on staging platform for reserves. These don't match!

**Expected behavior**
I would expect the Mumbai v3 subgraph to return me the same data (with the same contract address and user information) as the staging platform. Is the subgraph for a different aave v3 mumbai deployment while the staging is using a different deployment ?

**Comment by defispartan** [comment]
Hi @Kaushal1011 , it looks like this market was re-deployed to fix a faucet issue but wasn't updated on the subgraph, we'll get that fixed ASAP
