### ISSUE TITLE
Indexing status is failed in mainnet v2, v3

### ISSUE THREAD

**Issue by chenzongxiong** [aave/protocol-subgraphs#113]
**Describe the bug**
We follow readme to deploy subgraphs into our hosted graph-node locally, and found its status is FAILED when indexing. 

![image](https://github.com/aave/protocol-subgraphs/assets/8354165/d6a2ea70-581d-4b52-a36e-8b29954af21d)
![image](https://github.com/aave/protocol-subgraphs/assets/8354165/3697759f-2d92-43f2-9e3f-a1c429e96c08)
**To Reproduce**
commands to deploy subgraphs

```
VERSION=v2 npm run generate:schema
VERSION=v2 BLOCKCHAIN=ethereum NETWORK=mainnet npm run prepare:subgraph
```

we use node 18 instead of node 16. However, we don't think this will 

check block hash: a88a8f614fbfba005284bcc2b4841ebbe4b96a2950d24b30c975750c685386cd, which causes the failed status. 

**Expected behavior**
The indexing status should be in **healthy**

**Comment by defispartan** [comment]
This is a bug with the V3 reserve initializers, this [branch](https://github.com/aave/protocol-subgraphs/pull/106) has a fix for this issue. Once a test deployment for this PR is synced, it will be deployed to all networks and merged to main.

**Comment by chenzongxiong** [comment]
https://github.com/aave/protocol-subgraphs/blob/30b644a54099e3b7ebd1edb8f14c5f469807c000/schemas/v2.schema.graphql#L361


https://github.com/aave/protocol-subgraphs/blob/30b644a54099e3b7ebd1edb8f14c5f469807c000/src/mapping/lending-pool/lending-pool.ts#L314-L322


We need set `assetPriceUSD` optional, otherwise, the above source block will raise error since no `assetPriceUSD` is given. 

-> 

```
 assetPriceUSD: BigDecimal!  ->  assetPriceUSD: BigDecimal
```

**Comment by defispartan** [comment]
@chenzongxiong Thanks for reporting, V2 and V3 mappings were updated to always assign assetPriceUsd for flashloan entities, change is merged and deployed to all markets
