### ISSUE TITLE
Deploy Base subgraph

### ISSUE THREAD

**Issue by egorFiNE** [aave/protocol-subgraphs#116]
**Describe the bug**
There is no graph deployment for Aave v3 on the Base network.

**Comment by defispartan** [comment]
TheGraph hosted service does not [currently support](https://thegraph.com/docs/en/developing/supported-networks/#hosted-service) Base mainnet, we are exploring other options to provide a public subgraph endpoint for this market

**Comment by defispartan** [comment]
Now supported: https://github.com/aave/protocol-subgraphs?tab=readme-ov-file#production-networks
