### ISSUE TITLE
Contract source code Verification error 

### ISSUE THREAD

**Issue by Oba9526** [aave/protocol-subgraphs#124]
Error! Unable to locate ContractCode at 0x0
Is this a valid Contract Address ?Contractcode error ( Are you sure this is a contract address) that’s what it kept saying when I try to verify and publish my contract source code. It kept saying CONTRACT Code Error🙏

Please can you help me  with my contract verification 🙏🙏 It kept saying contract code error when I try to verify and publish my source code

**Comment by Obasimartins65** [comment]
![IMG_6306](https://github.com/aave/protocol-subgraphs/assets/142395658/77bcf0af-6ca5-4f3c-a25b-92604518074a)

**Comment by Oba9526** [comment]
![Uploading IMG_6306.jpeg…]()
