### ISSUE TITLE
Subgraph down

### ISSUE THREAD

**Issue by fubhy** [aave/protocol-subgraphs#130]
It appears that the subgraph hosted on The Graph's decentralized network has failed indexing: https://thegraph.com/explorer/subgraphs/Cd2gEDVeqnjBn1hSeqFMitw8Q1iiyV9FYUZkLNRcL87g

**Comment by defispartan** [comment]
All V3 subgraph have been re-deployed with updates to address Aave V3.1 interest rate strategy ABI change

Optimism is still syncing, rest should be resolved now

**Comment by fubhy** [comment]
Hi @defispartan, the Polygon subgraph has not been redeployed it seems! /cc @grothem

**Comment by grothem** [comment]
@fubhy Polygon should be fixed now, it took a while to finish indexing, but we published it yesterday
