### ISSUE TITLE
 Aave Polygon subgraph failed

### ISSUE THREAD

**Issue by AntonKaruna** [aave/protocol-subgraphs#133]
Hi. The subgraph for Aave Polygon has been in "failed" status for about a week now. Could you fix the problem please?

https://thegraph.com/explorer/subgraphs/Co2URyXjnxaw8WqxKyVHdirq9Ahhm5vcTs4dMedAq211?view=Indexers&chain=arbitrum-one

**Comment by KedziaPawel** [comment]
same issue here, it seems related to the other issue https://github.com/aave/protocol-subgraphs/issues/130 . Looks like not all subgraphs were redeployed

**Comment by grothem** [comment]
All subgraphs should be fixed now. There were a couple that were taking a while to index.
