### ISSUE TITLE
UserReserve currentATokenBalance/currentXXDebt don't count interest

### ISSUE THREAD

**Issue by wmwqyvon** [aave/protocol-subgraphs#93]
**Describe the bug**
currentATokenBalance, currentStableDebt, currentVariableDebt and currentTotalDebt return values without counting interest in. 

**To Reproduce**
For example, one user borrowed 1,000 USDC and his debt increased to 1,005 later, the currentTotalDebt will return 1,000,000,000 instead of 1,005,000,000.

**Comment by defispartan** [comment]
Current balances will only update for a specific user on the subgraph when that user performs an action. To compute the current aToken balance you multiply the users scaledATokenBalance by reserve.liquidityIndex. liquidityIndex is a continuously increasing variable which tracks accrued interest for all suppliers, and is updated whenever *any* user interacts with the reserve

**Comment by wmwqyvon** [comment]
Much appreciated. Is there any way to calculate the current stable debt balance?

**Comment by defispartan** [comment]
Yes, [this](https://docs.aave.com/developers/guides/rates-guide#how-is-yield-accrued) explains the variables used in this calculation
