### ISSUE TITLE
Indexing Error in Aave V2 subgraph

### ISSUE THREAD

**Issue by james3834** [aave/protocol-subgraphs#99]
the subgraph has an indexing error. This issue happens both in the hosted service https://thegraph.com/hosted-service/subgraph/aave/protocol-v2 and the decentralized service https://thegraph.com/explorer/subgraph?id=0x0d69090672c1e5a94e9aedfbc59558d18a78e1d3-0&view=Overview

**Comment by defispartan** [comment]
Fixed in #96
